/**
 * Utilidad para mapear 'imagen' a 'image' en los datos de arandelas
 */
export function mapFastenerImages(fastenerTable: Array<Record<string, string>>): Array<Record<string, string>> {
  return fastenerTable.map(row => {
    if (row.imagen) {
      return { ...row, image: row.imagen };
    }
    return row;
  });
}

export const FASTENERS: Record<string, Array<Record<string, string>>> = {
  'ARANDELA PLANA': [
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '5/32"', peso: '0.0007', marca: 'Importado', imagen: 'Arandela_Plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '3/16"', peso: '0.0010', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1/4"', peso: '0.0013', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '5/16"', peso: '0.0021', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '3/8"', peso: '0.0032', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1/2"', peso: '0.0075', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '5/8"', peso: '0.0110', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '3/4"', peso: '0.0140', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '7/8"', peso: '0.0190', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1"', peso: '0.0260', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1 1/4"', peso: '0.0340', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1 1/2"', peso: '0.0450', marca: 'Importado', imagen: 'arandela_plana' },
  ],
  'ARANDELA PLANA MILIMÉTRICA': [
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: 'M-5', peso: '0.0004', marca: 'Importado', imagen: 'Arandela_Plana_Milimétrica_Zincada' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: 'M-6', peso: '0.0010', marca: 'Importado', imagen: 'Arandela_Plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: 'M-8', peso: '0.0018', marca: 'Importado', imagen: 'Arandela_Plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: 'M-10', peso: '0.0035', marca: 'Importado', imagen: 'Arandela_Plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: 'M-12', peso: '0.0055', marca: 'Importado', imagen: 'Arandela_Plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: 'M-14', peso: '0.0080', marca: 'Importado', imagen: 'Arandela_Plana' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: 'M-18', peso: '0.0145', marca: 'Importado', imagen: 'Arandela_Plana' },
  ],
  'ARANDELA PLANA ZINCADA': [
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/32"', peso: '0.0007', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/16"', peso: '0.0010', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4"', peso: '0.0013', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/16"', peso: '0.0021', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/8"', peso: '0.0032', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/2"', peso: '0.0075', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/8"', peso: '0.0110', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/4"', peso: '0.0140', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '7/8"', peso: '0.0190', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1"', peso: '0.0260', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1 1/4"', peso: '0.0340', marca: 'Importado', imagen: 'arandela_plana' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1 1/2"', peso: '0.0450', marca: 'Importado', imagen: 'arandela_plana' },
  ],
  'ARANDELA PRESIÓN': [
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '5/32"', peso: '0.0004', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '3/16"', peso: '0.0006', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1/4"', peso: '0.0011', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '5/16"', peso: '0.0018', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '3/8"', peso: '0.0028', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1/2"', peso: '0.0059', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '5/8"', peso: '0.0109', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '3/4"', peso: '0.0185', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '7/8"', peso: '0.0270', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1"', peso: '0.0400', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1 1/4"', peso: '0.0520', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1 1/2"', peso: '0.1100', marca: 'Importado', imagen: 'arandela_de_presion' },
  ],
  'ARANDELA PRESIÓN MILIMÉTRICA': [
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: 'M-5', peso: '0.0005', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: 'M-6', peso: '0.0009', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: 'M-8', peso: '0.0016', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: 'M-10', peso: '0.0025', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: 'M-12', peso: '0.0038', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: 'M-14', peso: '0.0060', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: 'M-16', peso: '0.0088', marca: 'Importado', imagen: 'arandela_de_presion' },
  ],
  'ARANDELA PRESIÓN ZINCADA': [
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/32"', peso: '0.0004', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/16"', peso: '0.0006', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4"', peso: '0.0011', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-1010', acabado: 'incado', diametro: '5/16"', peso: '0.0018', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/8"', peso: '0.0028', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-1010', acabado: 'AZincado', diametro: '1/2"', peso: '0.0059', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/8"', peso: '0.0109', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/4"', peso: '0.0185', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '7/8"', peso: '0.0270', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1"', peso: '0.0400', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1 1/4"', peso: '0.0750', marca: 'Importado', imagen: 'arandela_de_presion' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1 1/2"', peso: '0.1100', marca: 'Importado', imagen: 'arandela_de_presion' },
  ],
  'AUTOPERFORANTE': [
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '8" x 1"', peso: '0.002', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '10" x 3/4"', peso: '0.003', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '10" x 1"', peso: '0.003', marca: 'Importado' },
  ],
  'PERNO COCHE UNC': [
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 3/4"', peso: '0.0078', marca: 'Importado', imagen: 'perno_coche' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1"', peso: '0.0092', marca: 'Importado', imagen: 'perno_coche' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1 1/2"', peso: '0.0124', marca: 'Importado', imagen: 'perno_coche' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 2"', peso: '0.0155', marca: 'Importado', imagen: 'perno_coche' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 2 1/2"', peso: '0.0186', marca: 'Importado', imagen: 'perno_coche' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 3"', peso: '0.0218', marca: 'Importado', imagen: 'perno_coche' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 3/4"', peso: '0.0135', marca: 'Importado', imagen: 'perno_coche' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 1"', peso: '0.0162', marca: 'Importado', imagen: 'perno_coche' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 1 1/2"', peso: '0.0215', marca: 'Importado', imagen: 'perno_coche' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 2"', peso: '0.0268', marca: 'Importado', imagen: 'perno_coche' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 2 1/2"', peso: '0.0321', marca: 'Importado', imagen: 'perno_coche' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 3"', peso: '0.0374', marca: 'Importado', imagen: 'perno_coche' },
  ],
  'PERNO DE EXPANSIÓN': [
    // --- ACERO INOXIDABLE C-304 ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1 3/4"', peso: '0.012', marca: 'Importado', imagen: 'perno_expansion_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 2"', peso: '0.015', marca: 'Importado', imagen: 'perno_expansion_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 2 1/4"', peso: '0.017', marca: 'Importado', imagen: 'perno_expansion_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 3 1/4"', peso: '0.021', marca: 'Importado', imagen: 'perno_expansion_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 4"', peso: '0.028', marca: 'Importado', imagen: 'perno_expansion_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 5"', peso: '0.035', marca: 'Importado', imagen: 'perno_expansion_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 2"', peso: '0.032', marca: 'Importado', imagen: 'perno_expansion_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 3"', peso: '0.043', marca: 'Importado', imagen: 'perno_expansion_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 4"', peso: '0.054', marca: 'Importado', imagen: 'perno_expansion_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 5"', peso: '0.065', marca: 'Importado', imagen: 'perno_expansion_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 6"', peso: '0.076', marca: 'Importado', imagen: 'perno_expansion_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 2 1/4"', peso: '0.079', marca: 'Importado', imagen: 'perno_expansion_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 3"', peso: '0.098', marca: 'Importado', imagen: 'perno_expansion_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 4"', peso: '0.125', marca: 'Importado', imagen: 'perno_expansion_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 5"', peso: '0.152', marca: 'Importado', imagen: 'perno_expansion_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/8" X 5"', peso: '0.245', marca: 'Importado', imagen: 'perno_expansion_inox' },

    // --- ZINCADO ---
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 2"', peso: '0.014', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 2 1/4"', peso: '0.015', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 3"', peso: '0.020', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 3 1/4"', peso: '0.023', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 4"', peso: '0.027', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 5"', peso: '0.034', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/8" X 2"', peso: '0.030', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/8" X 3"', peso: '0.084', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/8" X 3 1/4"', peso: '0.045', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/8" X 4"', peso: '0.052', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/8" X 5"', peso: '0.063', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/8" X 6"', peso: '0.074', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/2" X 2"', peso: '0.070', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/2" X 3"', peso: '0.095', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/2" X 4"', peso: '0.120', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/2" X 5"', peso: '0.148', marca: 'Importado', imagen: 'perno_expansion_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/2" X 6"', peso: '0.175', marca: 'Importado', imagen: 'perno_expansion_zinc' },
  ],
  'PERNO HEXAGONAL': [
    // --- DIÁMETRO 1/4" ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1/2"', peso: '0.0042', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 3/4"', peso: '0.0051', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1"', peso: '0.0060', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1 1/4"', peso: '0.0069', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1 1/2"', peso: '0.0078', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 2"', peso: '0.0096', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 2 1/2"', peso: '0.0114', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 3"', peso: '0.0132', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 4"', peso: '0.0168', marca: 'Importado', imagen: 'perno_hexagonal' },

    // --- DIÁMETRO 5/16" ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 1/2"', peso: '0.0075', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 3/4"', peso: '0.0090', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 1"', peso: '0.0105', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 1 1/2"', peso: '0.0135', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 2"', peso: '0.0165', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 2 1/2"', peso: '0.0195', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 3"', peso: '0.0225', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 4"', peso: '0.0285', marca: 'Importado', imagen: 'perno_hexagonal' },

    // --- DIÁMETRO 3/8" ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 1/2"', peso: '0.0118', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 3/4"', peso: '0.0142', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 1"', peso: '0.0166', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 1 1/2"', peso: '0.0214', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 2"', peso: '0.0262', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 2 1/2"', peso: '0.0310', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 3"', peso: '0.0358', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 4"', peso: '0.0454', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 5"', peso: '0.0550', marca: 'Importado', imagen: 'perno_hexagonal' },

    // --- DIÁMETRO 1/2" ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 3/4"', peso: '0.0290', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 1"', peso: '0.0335', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 1 1/2"', peso: '0.0425', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 2"', peso: '0.0515', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 2 1/2"', peso: '0.0605', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 3"', peso: '0.0695', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 4"', peso: '0.0875', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 5"', peso: '0.1055', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 6"', peso: '0.1235', marca: 'Importado', imagen: 'perno_hexagonal' },

    // --- DIÁMETROS MAYORES ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/8" X 2"', peso: '0.0850', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/8" X 3"', peso: '0.1180', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/8" X 4"', peso: '0.1510', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/8" X 5"', peso: '0.1840', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/8" X 6"', peso: '0.2170', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/4" X 2"', peso: '0.1380', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/4" X 3"', peso: '0.1850', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/4" X 4"', peso: '0.2320', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/4" X 5"', peso: '0.2790', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/4" X 6"', peso: '0.3260', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '7/8" X 3"', peso: '0.2650', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '7/8" X 4"', peso: '0.3350', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '7/8" X 5"', peso: '0.4050', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '7/8" X 6"', peso: '0.4750', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1" X 3"', peso: '0.3600', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1" X 4"', peso: '0.4500', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1" X 5"', peso: '0.5400', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1" X 6"', peso: '0.6300', marca: 'Importado', imagen: 'perno_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1" X 8"', peso: '0.8100', marca: 'Importado', imagen: 'perno_hexagonal' },
  ],
  'PERNO DE CABEZA PLANA CON HEXÁGONO INTERIOR (SOCKET)': [
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 1/2"', peso: '0.0018', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 3/4"', peso: '0.0024', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 1"', peso: '0.0031', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 1 1/2"', peso: '0.0045', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 2"', peso: '0.0058', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1/2"', peso: '0.0035', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 3/4"', peso: '0.0047', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1"', peso: '0.0058', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1 1/2"', peso: '0.0082', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 2"', peso: '0.0105', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 3"', peso: '0.0152', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 1/2"', peso: '0.0061', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 3/4"', peso: '0.0078', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 1"', peso: '0.0096', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 1 1/2"', peso: '0.0131', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 2"', peso: '0.0167', marca: 'Importado', imagen: 'perno_socket_plano' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 3"', peso: '0.0238', marca: 'Importado', imagen: 'perno_socket_plano' },
    ],
  'PERNO DE CABEZA CILÍNDRICA CON HEXÁGONO INTERIOR': [
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 1/2"', peso: '0.0022', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 3/4"', peso: '0.0028', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 1"', peso: '0.0034', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 1 1/2"', peso: '0.0046', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 2"', peso: '0.0058', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1/2"', peso: '0.0042', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 3/4"', peso: '0.0053', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1"', peso: '0.0070', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1 1/2"', peso: '0.0095', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 2"', peso: '0.0120', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 3"', peso: '0.0170', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 1/2"', peso: '0.0075', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 3/4"', peso: '0.0092', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 1"', peso: '0.0130', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 1 1/2"', peso: '0.0148', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 2"', peso: '0.0185', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 3"', peso: '0.0259', marca: 'Importado', imagen: 'perno_socket_cilindrico' },
    ],
  'PRISIONERO CON HEXÁGONO INTERIOR': [
    // --- DIÁMETRO 3/16" ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 1/4"', peso: '0.0006', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 5/16"', peso: '0.0008', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 3/8"', peso: '0.0010', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 1/2"', peso: '0.0013', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 3/4"', peso: '0.0020', marca: 'Importado', imagen: 'prisionero_allen' },

    // --- DIÁMETRO 1/4" ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 5/16"', peso: '0.0014', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 3/8"', peso: '0.0017', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1/2"', peso: '0.0022', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 3/4"', peso: '0.0033', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1"', peso: '0.0044', marca: 'Importado', imagen: 'prisionero_allen' },

    // --- DIÁMETRO 5/16" ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 5/16"', peso: '0.0021', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 3/8"', peso: '0.0026', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 1/2"', peso: '0.0035', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 3/4"', peso: '0.0052', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 1"', peso: '0.0070', marca: 'Importado', imagen: 'prisionero_allen' },

    // --- DIÁMETRO 3/8" ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 3/8"', peso: '0.0038', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 1/2"', peso: '0.0051', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 3/4"', peso: '0.0076', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 1"', peso: '0.0102', marca: 'Importado', imagen: 'prisionero_allen' },

    // --- DIÁMETRO 1/2" ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 1/2"', peso: '0.0085', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 3/4"', peso: '0.0128', marca: 'Importado', imagen: 'prisionero_allen' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2" X 1"', peso: '0.0171', marca: 'Importado', imagen: 'prisionero_allen' },
  ],
  'REMACHE': [
    // --- REMACHE ACERO INOXIDABLE C-304 ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/8" X 1/2"', peso: '0.0015', marca: 'Importado', imagen: 'remache_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/8" X 5/8"', peso: '0.0018', marca: 'Importado', imagen: 'remache_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/8" X 1"', peso: '0.0025', marca: 'Importado', imagen: 'remache_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/32" X 1/2"', peso: '0.0022', marca: 'Importado', imagen: 'remache_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/32" X 5/8"', peso: '0.0030', marca: 'Importado', imagen: 'remache_inox' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/32" X 1"', peso: '0.0042', marca: 'Importado', imagen: 'remache_inox' },

    // --- REMACHE DE ALUMINIO ---
    { calidad: '-', acabado: 'Aluminio', diametro: '1/8" X 3/8"', peso: '0.0008', marca: 'Importado', imagen: 'remache_aluminio' },
    { calidad: '-', acabado: 'Aluminio', diametro: '1/8" X 1/2"', peso: '0.0010', marca: 'Importado', imagen: 'remache_aluminio' },
    { calidad: '-', acabado: 'Aluminio', diametro: '1/8" X 5/8"', peso: '0.0012', marca: 'Importado', imagen: 'remache_aluminio' },
    { calidad: '-', acabado: 'Aluminio', diametro: '1/8" X 3/4"', peso: '0.0014', marca: 'Importado', imagen: 'remache_aluminio' },
    { calidad: '-', acabado: 'Aluminio', diametro: '1/8" X 1"', peso: '0.0018', marca: 'Importado', imagen: 'remache_aluminio' },
    { calidad: '-', acabado: 'Aluminio', diametro: '5/32" X 3/8"', peso: '0.0014', marca: 'Importado', imagen: 'remache_aluminio' },
    { calidad: '-', acabado: 'Aluminio', diametro: '5/32" X 1/2"', peso: '0.0017', marca: 'Importado', imagen: 'remache_aluminio' },
    { calidad: '-', acabado: 'Aluminio', diametro: '5/32" X 5/8"', peso: '0.0020', marca: 'Importado', imagen: 'remache_aluminio' },
    { calidad: '-', acabado: 'Aluminio', diametro: '5/32" X 3/4"', peso: '0.0023', marca: 'Importado', imagen: 'remache_aluminio' },
    { calidad: '-', acabado: 'Aluminio', diametro: '5/32" X 1"', peso: '0.0030', marca: 'Importado', imagen: 'remache_aluminio' },
    { calidad: '-', acabado: 'Aluminio', diametro: '3/16" X 1/2"', peso: '0.0025', marca: 'Importado', imagen: 'remache_aluminio' },
    { calidad: '-', acabado: 'Aluminio', diametro: '3/16" X 5/8"', peso: '0.0030', marca: 'Importado', imagen: 'remache_aluminio' },
    { calidad: '-', acabado: 'Aluminio', diametro: '3/16" X 3/4"', peso: '0.0035', marca: 'Importado', imagen: 'remache_aluminio' },
    { calidad: '-', acabado: 'Aluminio', diametro: '3/16" X 1"', peso: '0.0045', marca: 'Importado', imagen: 'remache_aluminio' },
  ],
  'ESPÁRRAGO ROSCADO': [
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1/8"', peso: '0.049', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '3/16"', peso: '0.110', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1/4"', peso: '0.183', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '5/16"', peso: '0.290', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '3/8"', peso: '0.430', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1/2"', peso: '0.789', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '5/8"', peso: '1.256', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '3/4"', peso: '1.832', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '7/8"', peso: '2.520', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1"', peso: '3.310', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1 1/4"', peso: '5.320', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1 1/2"', peso: '7.750', marca: 'Importado' },
  ],
  'STOVE BOLT DE CABEZA PAN': [
    // --- DIÁMETRO 1/8" ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/8" X 1/2"', peso: '0.0012', marca: 'Importado', imagen: 'perno_stove_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/8" X 3/4"', peso: '0.0016', marca: 'Importado', imagen: 'perno_stove_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/8" X 1"', peso: '0.0020', marca: 'Importado', imagen: 'perno_stove_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/8" X 1 1/2"', peso: '0.0028', marca: 'Importado', imagen: 'perno_stove_pan' },

    // --- DIÁMETRO 5/32" ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/32" X 1/2"', peso: '0.0018', marca: 'Importado', imagen: 'perno_stove_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/32" X 3/4"', peso: '0.0023', marca: 'Importado', imagen: 'perno_stove_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/32" X 1"', peso: '0.0028', marca: 'Importado', imagen: 'perno_stove_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/32" X 1 1/2"', peso: '0.0038', marca: 'Importado', imagen: 'perno_stove_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/32" X 2"', peso: '0.0048', marca: 'Importado', imagen: 'perno_stove_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/32" X 2 1/2"', peso: '0.0058', marca: 'Importado', imagen: 'perno_stove_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/32" X 3"', peso: '0.0068', marca: 'Importado', imagen: 'perno_stove_pan' },

    // --- DIÁMETRO 3/16" ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 1/2"', peso: '0.0024', marca: 'Importado', imagen: 'perno_stove_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 3/4"', peso: '0.0030', marca: 'Importado', imagen: 'perno_stove_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 1"', peso: '0.0040', marca: 'Importado', imagen: 'perno_stove_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 1 1/2"', peso: '0.0050', marca: 'Importado', imagen: 'perno_stove_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 2"', peso: '0.0060', marca: 'Importado', imagen: 'perno_stove_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 2 1/2"', peso: '0.0075', marca: 'Importado', imagen: 'perno_stove_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16" X 3"', peso: '0.0090', marca: 'Importado', imagen: 'perno_stove_pan' },
  ],
  'STOVE BOLT ZINCADO': [
    // --- DIÁMETRO 1/8" ---
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/8" X 1/2"', peso: '0.0011', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/8" X 5/8"', peso: '0.0013', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/8" X 3/4"', peso: '0.0015', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/8" X 1"', peso: '0.0019', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/8" X 1 1/2"', peso: '0.0027', marca: 'Importado', imagen: 'stove_bolt_zinc' },

    // --- DIÁMETRO 5/32" ---
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/32" X 1/2"', peso: '0.0017', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/32" X 5/8"', peso: '0.0020', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/32" X 3/4"', peso: '0.0023', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/32" X 1"', peso: '0.0028', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/32" X 1 1/4"', peso: '0.0033', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/32" X 1 1/2"', peso: '0.0038', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/32" X 2"', peso: '0.0048', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/32" X 3"', peso: '0.0068', marca: 'Importado', imagen: 'stove_bolt_zinc' },

    // --- DIÁMETRO 3/16" ---
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/16" X 1/2"', peso: '0.0024', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/16" X 5/8"', peso: '0.0027', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/16" X 3/4"', peso: '0.0031', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/16" X 1"', peso: '0.0041', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/16" X 1 1/4"', peso: '0.0049', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/16" X 1 1/2"', peso: '0.0057', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/16" X 2"', peso: '0.0073', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/16" X 3"', peso: '0.0105', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/16" X 4"', peso: '0.0137', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/16" X 5"', peso: '0.0169', marca: 'Importado', imagen: 'stove_bolt_zinc' },

    // --- DIÁMETRO 1/4" ---
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 1/2"', peso: '0.0048', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 5/8"', peso: '0.0055', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 3/4"', peso: '0.0062', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 1"', peso: '0.0076', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 1 1/4"', peso: '0.0089', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 1 1/2"', peso: '0.0103', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 2"', peso: '0.0131', marca: 'Importado', imagen: 'stove_bolt_zinc' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 3"', peso: '0.0187', marca: 'Importado', imagen: 'stove_bolt_zinc' },
  ],
  'TACOS DE EXPANSIÓN': [
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1/4"', peso: '0.01', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '5/16"', peso: '---', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '3/8"', peso: '0.01', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1/2"', peso: '---', marca: 'Importado' },
  ],
  'TARUGOS': [
    { acabado: 'Plástico Verde', diametro: '1/4"', peso: '0.001', marca: 'Importado' },
    { acabado: 'Plástico Blanco', diametro: '1/4"', peso: '0.001', marca: 'Importado' },
    { acabado: 'Plástico Azul', diametro: '5/16"', peso: '0.001', marca: 'Importado' },
    { acabado: 'Plástico Naranja', diametro: '3/8"', peso: '0.002', marca: 'Importado' },
  ],
  'TIRAFÓN': [
    // --- TIRAFÓN HEXAGONAL ACERO INOXIDABLE C-304 ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1"', peso: '0.0070', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 1 1/2"', peso: '0.0090', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 2"', peso: '0.0115', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4" X 3"', peso: '0.0165', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 1"', peso: '0.0110', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 1 1/2"', peso: '0.0145', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 2"', peso: '0.0185', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 2 1/2"', peso: '0.0225', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16" X 3"', peso: '0.0265', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 1"', peso: '0.0160', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 1 1/2"', peso: '0.0210', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 2"', peso: '0.0270', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 2 1/2"', peso: '0.0330', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 3"', peso: '0.0390', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8" X 4"', peso: '0.0510', marca: 'Importado', imagen: 'tirafon_hexagonal' },

    // --- TIRAFÓN HEXAGONAL ZINCADO (CALIDAD C-1010) ---
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 1"', peso: '0.0070', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 1 1/2"', peso: '0.0080', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 2"', peso: '0.0100', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4" X 3"', peso: '0.0155', marca: 'Importado', imagen: 'tirafon_hexagonal' },
    ],
  'TORNILLO AUTORROSCANTE DE CABEZA PAN': [
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '8 X 1/2"', peso: '0.0016', marca: 'Importado', imagen: 'autorroscante_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '8 X 5/8"', peso: '0.0018', marca: 'Importado', imagen: 'autorroscante_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '8 X 3/4"', peso: '0.0020', marca: 'Importado', imagen: 'autorroscante_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '8 X 1"', peso: '0.0020', marca: 'Importado', imagen: 'autorroscante_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '8 X 1 1/4"', peso: '0.0024', marca: 'Importado', imagen: 'autorroscante_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '8 X 1 1/2"', peso: '0.0028', marca: 'Importado', imagen: 'autorroscante_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '8 X 2"', peso: '0.0035', marca: 'Importado', imagen: 'autorroscante_pan' },

    // --- DIÁMETRO #10 ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 1/2"', peso: '0.0020', marca: 'Importado', imagen: 'autorroscante_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 5/8"', peso: '0.0020', marca: 'Importado', imagen: 'autorroscante_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 3/4"', peso: '0.0025', marca: 'Importado', imagen: 'autorroscante_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 1"', peso: '0.0030', marca: 'Importado', imagen: 'autorroscante_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 1 1/2"', peso: '0.0040', marca: 'Importado', imagen: 'autorroscante_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 2"', peso: '0.0051', marca: 'Importado', imagen: 'autorroscante_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 2 1/2"', peso: '0.0062', marca: 'Importado', imagen: 'autorroscante_pan' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 3"', peso: '0.0073', marca: 'Importado', imagen: 'autorroscante_pan' },
  ],
  'TORNILLO AUTORROSCANTE DE CABEZA PLANA': [
    // --- DIÁMETRO #6 ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '6 X 7/8"', peso: '0.0010', marca: 'Importado', imagen: 'autorroscante_plana' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '6 X 1"', peso: '0.0010', marca: 'Importado', imagen: 'autorroscante_plana' },

    // --- DIÁMETRO #7 ---
    // --- DIÁMETRO #8 ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '8 X 1/2"', peso: '0.0014', marca: 'Importado', imagen: 'autorroscante_plana' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '8 X 5/8"', peso: '0.0016', marca: 'Importado', imagen: 'autorroscante_plana' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '8 X 3/4"', peso: '0.0018', marca: 'Importado', imagen: 'autorroscante_plana' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '8 X 1"', peso: '0.0020', marca: 'Importado', imagen: 'autorroscante_plana' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '8 X 1 1/4"', peso: '0.0022', marca: 'Importado', imagen: 'autorroscante_plana' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '8 X 1 1/2"', peso: '0.0026', marca: 'Importado', imagen: 'autorroscante_plana' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '8 X 2"', peso: '0.0032', marca: 'Importado', imagen: 'autorroscante_plana' },

    // --- DIÁMETRO #10 ---
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 1/2"', peso: '0.0018', marca: 'Importado', imagen: 'autorroscante_plana' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 5/8"', peso: '0.0018', marca: 'Importado', imagen: 'autorroscante_plana' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 3/4"', peso: '0.0023', marca: 'Importado', imagen: 'autorroscante_plana' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 1"', peso: '0.0028', marca: 'Importado', imagen: 'autorroscante_plana' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 1 1/2"', peso: '0.0038', marca: 'Importado', imagen: 'autorroscante_plana' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 2"', peso: '0.0048', marca: 'Importado', imagen: 'autorroscante_plana' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 2 1/2"', peso: '0.0058', marca: 'Importado', imagen: 'autorroscante_plana' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '10 X 3"', peso: '0.0069', marca: 'Importado', imagen: 'autorroscante_plana' },
  ],
  'TUERCA CIEGA': [
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16"', peso: '0.0030', marca: 'Importado', imagen: 'tuerca_ciega' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4"', peso: '0.0045', marca: 'Importado', imagen: 'tuerca_ciega' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16"', peso: '0.0100', marca: 'Importado', imagen: 'tuerca_ciega' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8"', peso: '0.0150', marca: 'Importado', imagen: 'tuerca_ciega' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2"', peso: '0.0280', marca: 'Importado', imagen: 'tuerca_ciega' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/8"', peso: '0.0450', marca: 'Importado', imagen: 'tuerca_ciega' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/4"', peso: '0.0720', marca: 'Importado', imagen: 'tuerca_ciega' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '7/8"', peso: '0.1150', marca: 'Importado', imagen: 'tuerca_ciega' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1"', peso: '0.1650', marca: 'Importado', imagen: 'tuerca_ciega' },
  ],
  'TUERCA HEXAGONAL': [
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '5/32"', peso: '---', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1/4"', peso: '0.003', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '5/16"', peso: '0.005', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '3/8"', peso: '0.007', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '1/2"', peso: '0.016', marca: 'Importado' },
    { calidad: 'C-304', acabado: 'Acero inoxidable', diametro: '5/8"', peso: '0.032', marca: 'Importado' },
  ],
  'TUERCA HEXAGONAL MILIMETRICA': [
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: 'M-5', peso: '0.0012', marca: 'Importado', imagen: 'tuerca_hexagonal_metrica' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: 'M-6', peso: '0.0025', marca: 'Importado', imagen: 'tuerca_hexagonal_metrica' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: 'M-8', peso: '0.0052', marca: 'Importado', imagen: 'tuerca_hexagonal_metrica' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: 'M-10', peso: '0.0116', marca: 'Importado', imagen: 'tuerca_hexagonal_metrica' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: 'M-12', peso: '0.0173', marca: 'Importado', imagen: 'tuerca_hexagonal_metrica' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: 'M-14', peso: '0.0250', marca: 'Importado', imagen: 'tuerca_hexagonal_metrica' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: 'M-18', peso: '0.0490', marca: 'Importado', imagen: 'tuerca_hexagonal_metrica' },
  ],
  'TUERCA MARIPOSA': [
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/32"', peso: '0.0030', marca: 'Importado', imagen: 'tuerca_mariposa' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/16"', peso: '0.0042', marca: 'Importado', imagen: 'tuerca_mariposa' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/4"', peso: '0.0075', marca: 'Importado', imagen: 'tuerca_mariposa' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/16"', peso: '0.0130', marca: 'Importado', imagen: 'tuerca_mariposa' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/8"', peso: '0.0240', marca: 'Importado', imagen: 'tuerca_mariposa' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1/2"', peso: '0.0520', marca: 'Importado', imagen: 'tuerca_mariposa' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '5/8"', peso: '0.0950', marca: 'Importado', imagen: 'tuerca_mariposa' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '3/4"', peso: '0.1550', marca: 'Importado', imagen: 'tuerca_mariposa' },
    { calidad: 'C-304', acabado: 'Acero Inoxidable', diametro: '1"', peso: '0.2400', marca: 'Importado', imagen: 'tuerca_mariposa' },
  ],
  'TUERCA ZINCADO': [
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/32"', peso: '0.0010', marca: 'Importado', imagen: 'tuerca_zincado' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/4"', peso: '0.0030', marca: 'Importado', imagen: 'tuerca_zincado' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/16"', peso: '0.0070', marca: 'Importado', imagen: 'tuerca_zincado' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/8"', peso: '0.0160', marca: 'Importado', imagen: 'tuerca_zincado' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1/2"', peso: '0.0310', marca: 'Importado', imagen: 'tuerca_zincado' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '5/8"', peso: '0.0510', marca: 'Importado', imagen: 'tuerca_zincado' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '3/4"', peso: '0.0820', marca: 'Importado', imagen: 'tuerca_zincado' },
    { calidad: 'C-1010', acabado: 'Zincado', diametro: '1"', peso: '0.1850', marca: 'Importado', imagen: 'tuerca_zincado' },
  ],
};

export default FASTENERS;